name: Golang Windows amd64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Go environment
      uses: actions/setup-go@v3.3.0
      with:
        go-version: 1.18
        architecture: amd64

    - name: Build
      run: env GOOS=windows GOARCH=amd64 go build .
